register pass tests
meaboutsoftware/SuperSimpleArchitecture pull request #2
Opened 2023-03-17 17:59 UTC by kamilbaczek

2023-03-18 11:19 UTC, meaboutsoftware requested changes

2023-03-18 11:19 UTC, meaboutsoftware commented on Src/Fitnet/Passes/Api/GetAll/ViewModels/PassListItemDto.cs
> +namespace SuperSimpleArchitecture.Fitnet.Passes.Api.GetAll.ViewModels;
3 things here:

- the idea fro miro was to not to create Api/Infra/Domain folders but to have it all in one (architecture 4+1)
- is there any business process named GetAll or are we going to use GetAll from other modules? According to what we had in the diagram, there is no need for that, there are only 2 processes - RegisterPass and MarkPassAsExpired, so there is no GetAll
- As we do not code in MVC, I would suggest to not to have ViewModels but more something like Responses (request->API->response)

WDYT? :)

2023-03-18 11:19 UTC, meaboutsoftware commented on Src/Fitnet.IntegrationTests/Common/TestEngine/DockerDatabase.cs
> +public sealed class DockerDatabase : IAsyncLifetime
I would suggest to name it ContainerDatabase to not to be "Docker" specific

2023-03-18 11:19 UTC, meaboutsoftware commented on Src/Fitnet.IntegrationTests/Fitnet.IntegrationTests.csproj
>          <PackageReference Include="MassTransit" Version="8.0.12" />
For what do we use today MassTransit? Haven't spotted it before :)

2023-03-18 11:19 UTC, meaboutsoftware commented on Src/Fitnet.IntegrationTests/Passes/Register/RegisterPassTests.cs
> +        var registerPassRequest = new RegisterPassRequest(Guid.NewGuid(), _faker.Date.Recent(),_faker.Date.Future());
Let's do comments:

// Arrange

// Act

// Assert

WDYT?

2023-03-18 11:38 UTC, kamilbaczek commented on Src/Fitnet.IntegrationTests/Fitnet.IntegrationTests.csproj
>          <PackageReference Include="MassTransit" Version="8.0.12" />
Yeah. Reference is to remove

2023-03-18 11:50 UTC, kamilbaczek commented on Src/Fitnet.IntegrationTests/Common/TestEngine/DockerDatabase.cs
> +public sealed class DockerDatabase : IAsyncLifetime
I thought about it. I will rename

2023-03-18 11:50 UTC, kamilbaczek commented on Src/Fitnet.IntegrationTests/Passes/Register/RegisterPassTests.cs
> +        var registerPassRequest = new RegisterPassRequest(Guid.NewGuid(), _faker.Date.Recent(),_faker.Date.Future());
I have seen this practice. We can apply it

2023-03-18 11:56 UTC, kamilbaczek commented on Src/Fitnet/Passes/Api/GetAll/ViewModels/PassListItemDto.cs
> +namespace SuperSimpleArchitecture.Fitnet.Passes.Api.GetAll.ViewModels;
Point 2. I think we need read API to even validare that our process persist data correctly.

2023-03-18 17:01 UTC, kamilbaczek commented on Src/Fitnet.IntegrationTests/Passes/Register/RegisterPassTests.cs
> +        var registerPassRequest = new RegisterPassRequest(Guid.NewGuid(), _faker.Date.Recent(),_faker.Date.Future());
Applied

2023-03-18 17:03 UTC, kamilbaczek commented on Src/Fitnet.IntegrationTests/Common/TestEngine/DockerDatabase.cs
> +public sealed class DockerDatabase : IAsyncLifetime
renamed

2023-03-18 17:03 UTC, kamilbaczek commented on Src/Fitnet.IntegrationTests/Fitnet.IntegrationTests.csproj
>          <PackageReference Include="MassTransit" Version="8.0.12" />
Reference removed

2023-03-18 17:04 UTC, kamilbaczek commented on Src/Fitnet/Passes/Api/GetAll/ViewModels/PassListItemDto.cs
> +namespace SuperSimpleArchitecture.Fitnet.Passes.Api.GetAll.ViewModels;
Point 1. You are right I will prepare simplified version

2023-03-18 17:05 UTC, kamilbaczek commented on Src/Fitnet/Passes/Api/GetAll/ViewModels/PassListItemDto.cs
> +namespace SuperSimpleArchitecture.Fitnet.Passes.Api.GetAll.ViewModels;
Point 3. Good point. I will rename this model

2023-03-19 07:39 UTC, meaboutsoftware commented on Src/Fitnet/Passes/Api/GetAll/ViewModels/PassListItemDto.cs
> +namespace SuperSimpleArchitecture.Fitnet.Passes.Api.GetAll.ViewModels;
For now ok but we need to discuss it :)

2023-03-19 07:41 UTC, meaboutsoftware requested changes

2023-03-19 07:41 UTC, meaboutsoftware commented on Src/Fitnet/Passes/GetAll/ViewModels/PassListItemDto.cs
> +namespace SuperSimpleArchitecture.Fitnet.Passes.GetAll.ViewModels;
Namespace also to be renamed, e.g. to Dtos

2023-03-19 07:41 UTC, meaboutsoftware commented on Src/Fitnet/Passes/GetAll/ViewModels/PassListItemDto.cs
> +public record struct PassListItemDto(Guid Id, Guid CustomerId, DateTimeOffset From, DateTimeOffset To);
When we use Passes in one place, it would be cool to stick to convention e.g. PassesItemDto or PassDto

2023-03-19 07:41 UTC, meaboutsoftware commented on Src/Fitnet/Passes/GetAll/ViewModels/PassesResponse.cs
> +namespace SuperSimpleArchitecture.Fitnet.Passes.GetAll.ViewModels;
Same here with namespace

2023-03-19 09:02 UTC, kamilbaczek commented on Src/Fitnet/Passes/GetAll/ViewModels/PassListItemDto.cs
> +public record struct PassListItemDto(Guid Id, Guid CustomerId, DateTimeOffset From, DateTimeOffset To);
Yep :D

2023-03-19 09:02 UTC, kamilbaczek commented on Src/Fitnet/Passes/GetAll/ViewModels/PassListItemDto.cs
> +namespace SuperSimpleArchitecture.Fitnet.Passes.GetAll.ViewModels;
Fixed

2023-03-19 09:03 UTC, kamilbaczek commented on Src/Fitnet/Passes/GetAll/ViewModels/PassesResponse.cs
> +namespace SuperSimpleArchitecture.Fitnet.Passes.GetAll.ViewModels;
Fixed

2023-03-19 09:03 UTC, kamilbaczek commented on Src/Fitnet/Passes/Api/GetAll/ViewModels/PassListItemDto.cs
> +namespace SuperSimpleArchitecture.Fitnet.Passes.Api.GetAll.ViewModels;
Great :D we will discuss

2023-03-19 14:14 UTC, meaboutsoftware approved these changes

2023-03-19 19:33 UTC, merged