Add business rule to sign contract
meaboutsoftware/SuperSimpleArchitecture pull request #21
Opened 2023-04-08 14:00 UTC by meaboutsoftware

This PR includes work related to:

- introduction of a business rule that checks if contract can be signed or not
- integration of the business rule in contract entity on signing action
- fix to cancellation token passing in 2 endpoints
- moving usings to a namespace

2023-04-10 08:30 UTC, kamilbaczek commented on Src/Fitnet.IntegrationTests/Contracts/SignContract/SignContractRequestFaker.cs
> +    public SignContractRequestFaker(DateTimeOffset signedAt)
```suggestion
    public SignContractRequestFaker(DateTimeOffset signedAt) =>
        CustomInstantiator(_ =>
            new SignContractRequest(signedAt)
        );```

2023-04-10 08:32 UTC, kamilbaczek commented on Src/Fitnet.IntegrationTests/Contracts/SignContract/SignContractTests.cs
> +    private static DateTimeOffset GetValidSignedAtDate()
```suggestion
    private static DateTimeOffset GetValidSignedAtDate() => 
        DateTimeOffset.Now.AddDays(1).ToUniversalTime();
```

2023-04-10 08:34 UTC, kamilbaczek commented on Src/Fitnet.UnitTests/Contracts/SignContract/BusinessRules/ContractCanOnlyBeSignedWithin30DaysFromPreparationTests.cs
> +    public void Given_signed_at_date_which_is_more_than_30_days_from_prepared_at_date_Then_validation_should_throw()
Could we make test parameterized. 
to be able to change test data like 31 without changing of the test body?

2023-04-10 08:35 UTC, kamilbaczek commented on Src/Fitnet.UnitTests/Contracts/SignContract/BusinessRules/ContractCanOnlyBeSignedWithin30DaysFromPreparationTests.cs
> +                    DateTimeOffset.Now.AddDays(29)));;
Please check this class there is two places with ;; instead ;

2023-04-10 08:39 UTC, kamilbaczek requested changes
Could you change a few minor suggestions?

2023-04-10 16:09 UTC, meaboutsoftware commented on Src/Fitnet.IntegrationTests/Contracts/SignContract/SignContractRequestFaker.cs
> +    public SignContractRequestFaker(DateTimeOffset signedAt)
Done

2023-04-10 16:10 UTC, meaboutsoftware commented on Src/Fitnet.IntegrationTests/Contracts/SignContract/SignContractTests.cs
> +    private static DateTimeOffset GetValidSignedAtDate()
Done

2023-04-10 16:12 UTC, meaboutsoftware commented on Src/Fitnet.UnitTests/Contracts/SignContract/BusinessRules/ContractCanOnlyBeSignedWithin30DaysFromPreparationTests.cs
> +                    DateTimeOffset.Now.AddDays(29)));;
Done, good spot!

2023-04-10 16:15 UTC, meaboutsoftware commented on Src/Fitnet.UnitTests/Contracts/SignContract/BusinessRules/ContractCanOnlyBeSignedWithin30DaysFromPreparationTests.cs
> +    public void Given_signed_at_date_which_is_more_than_30_days_from_prepared_at_date_Then_validation_should_throw()
In this particular case I am more into direction of having separate test cases without parametrisation. The reason is that:

- there are 3 test cases
- each test checks concrete border case
- 2 tests passes, 1 test throws (different expectations)

Usually I am for parametrisation, however here I would vote to do it this way (it is more readable)

2023-04-11 06:58 UTC, kamilbaczek approved these changes
Quick fixes! Thanks

2023-04-11 18:10 UTC, kamilbaczek approved these changes
Good job!

2023-04-11 18:10 UTC, merged