Feature/inmemory event bust tests
meaboutsoftware/SuperSimpleArchitecture pull request #24
Opened 2023-04-15 07:30 UTC by kamilbaczek

2023-04-17 04:18 UTC, kamilbaczek commented on Src/Fitnet/Shared/Events/IIntegrationEvent.cs
> +internal interface IIntegrationEventHandler<in TEvent> : INotificationHandler<TEvent> where TEvent : IIntegrationEvent
Extract file

2023-04-17 06:14 UTC, meaboutsoftware requested changes

2023-04-17 06:14 UTC, meaboutsoftware commented on Src/Fitnet.IntegrationTests/Shared/Events/EventBus/InMemory/InMemoryEventBusTests.cs
> +         await eventBus.PublishAsync(fakeEvent, CancellationToken.None);
Remove not needed space

2023-04-17 06:14 UTC, meaboutsoftware commented on Src/Fitnet.IntegrationTests/Shared/Events/EventBus/InMemory/InMemoryEventBusTests.cs
> +    public async Task Given_valid_event_Then_event_should_be_consumed()
Maybe Given_valid_event_**published**_Then...?

Especially as we will have Subscribe as well in this class, then it makes sense to distinguish it.

Btw. That's why I prefer one of these approaches (we won't change it but as info) either:

Should...When - ShouldBeConsumed_WhenValidEventPublished
Given...When...Then - GivenValidEvent_WhenPublished_ThenItShouldBeConsumed

:)

2023-04-17 06:14 UTC, meaboutsoftware commented on Src/Fitnet/Shared/Events/IIntegrationEvent.cs
> +internal interface IIntegrationEventHandler<in TEvent> : INotificationHandler<TEvent> where TEvent : IIntegrationEvent
Why do you think it makes sense? :) Both are completely related to each other

2023-04-18 18:28 UTC, kamilbaczek commented on Src/Fitnet/Shared/Events/IIntegrationEvent.cs
> +internal interface IIntegrationEventHandler<in TEvent> : INotificationHandler<TEvent> where TEvent : IIntegrationEvent
File name is IIntegrationEvent

2023-04-18 18:35 UTC, kamilbaczek commented on Src/Fitnet.IntegrationTests/Shared/Events/EventBus/InMemory/InMemoryEventBusTests.cs
> +    public async Task Given_valid_event_Then_event_should_be_consumed()
@meaboutsoftware thanks for this advice. I will try this approach in another project

2023-04-19 05:59 UTC, meaboutsoftware approved these changes

2023-04-19 07:00 UTC, merged