Add exception middleware
meaboutsoftware/SuperSimpleArchitecture pull request #26
Opened 2023-04-17 07:45 UTC by meaboutsoftware

This PR contains changes related to following areas:

- Exception middleware that handles Business rule validation exceptions and all other exceptions (as internal server error)
- Negative integration tests that were missing for contract preparation
- Negative integration tests that were missing for contract signing

2023-04-18 18:46 UTC, kamilbaczek requested changes

2023-04-18 18:46 UTC, kamilbaczek commented on Src/Fitnet/Program.cs
> +app.UseMiddleware<ExceptionMiddleware>();
Could you wrap it in extensions method. 

in result we could have.

app.UseErrorHandling();

2023-04-18 18:46 UTC, kamilbaczek commented on Src/Fitnet/ExceptionMiddleware.cs
> +        var result = JsonConvert.SerializeObject(new
Have we benefit from using dynamic over strongly typed record like "internal record ErrorDetails(string Message)"

2023-04-18 18:46 UTC, kamilbaczek commented on Src/Fitnet.UnitTests/ExceptionMiddlewareTests.cs
> +    private readonly HttpContext _context;
could we add enter here?

2023-04-18 18:46 UTC, kamilbaczek commented on Src/Fitnet.UnitTests/ExceptionMiddlewareTests.cs
> +    {
public ExceptionMiddlewareTests()  => _context = GetHttpContext();

2023-04-19 12:14 UTC, meaboutsoftware commented on Src/Fitnet/ExceptionMiddleware.cs
> +        var result = JsonConvert.SerializeObject(new
Done

2023-04-19 12:16 UTC, meaboutsoftware commented on Src/Fitnet.UnitTests/ExceptionMiddlewareTests.cs
> +    {
Done

2023-04-19 12:16 UTC, meaboutsoftware commented on Src/Fitnet.UnitTests/ExceptionMiddlewareTests.cs
> +    private readonly HttpContext _context;
Done

2023-04-19 12:16 UTC, kamilbaczek requested changes

2023-04-19 12:16 UTC, kamilbaczek commented on Src/Fitnet/ExceptionMiddleware.cs
> +internal class ExceptionMiddleware
Could be sealed?

2023-04-19 12:24 UTC, meaboutsoftware commented on Src/Fitnet/Program.cs
> +app.UseMiddleware<ExceptionMiddleware>();
Done

2023-04-19 13:21 UTC, kamilbaczek approved these changes

2023-04-19 13:58 UTC, merged