Mark pass as expired tests
meaboutsoftware/SuperSimpleArchitecture pull request #7
Opened 2023-03-25 10:42 UTC by kamilbaczek

2023-03-25 13:38 UTC, meaboutsoftware requested changes

2023-03-25 13:38 UTC, meaboutsoftware commented on Src/Fitnet.IntegrationTests/Common/TestEngine/Configuration/ConfigurationExtensions.cs
> +    internal static WebApplicationFactory<T> WithContainerDatabaseConfigured<T>(this WebApplicationFactory<T> webApplicationFactory, string connectionString)
That's fine, good enough :)

2023-03-25 13:38 UTC, meaboutsoftware commented on Src/Fitnet/ApiPaths.cs
> +    public static class Passes
Maybe it would make sense to move it to passes module - this way we do not have any leak to the root

2023-03-25 13:38 UTC, meaboutsoftware commented on Src/Fitnet/ApiPaths.cs
> +        public const string MarkPassAsExpired = $"{Api}/passes/{{id}}/mark-as-expired";
Btw. maybe instead of /passes/{{id}}/mark-as-expired we could just follow RESTful API?

So, to get pass it would be passes/id with GET.
To mark as expired it would be passes/id with PUT/PATCH.
etc.

What do you think?

2023-03-26 07:57 UTC, kamilbaczek commented on Src/Fitnet/ApiPaths.cs
> +        public const string MarkPassAsExpired = $"{Api}/passes/{{id}}/mark-as-expired";
This path is correct in REST API Standard. I assumed when we will have move patch endpoints we won't be forced to go back and change url in pervious endpoint. For now when we have only one endpoint to optimize simplicity I can change it to url to version without action name.

2023-03-26 08:17 UTC, kamilbaczek commented on Src/Fitnet/ApiPaths.cs
> +    public static class Passes
Done :D

2023-03-26 08:17 UTC, kamilbaczek commented on Src/Fitnet/ApiPaths.cs
> +        public const string MarkPassAsExpired = $"{Api}/passes/{{id}}/mark-as-expired";
Changed :D

2023-03-26 09:52 UTC, meaboutsoftware commented on Src/Fitnet/ApiPaths.cs
> +        public const string MarkPassAsExpired = $"{Api}/passes/{{id}}/mark-as-expired";
Yep, it was a shortcut for my thinking - I would go as simple as possible as there won't be more endpoints here

2023-03-26 09:52 UTC, merged