Create ci.yml
meaboutsoftware/SuperSimpleArchitecture pull request #8
Opened 2023-03-25 11:27 UTC by kamilbaczek

2023-03-25 11:54 UTC, kamilbaczek commented
https://github.com/meaboutsoftware/SuperSimpleArchitecture/pull/7 when this PR will be merged tests will pass .

2023-03-25 13:42 UTC, meaboutsoftware requested changes

2023-03-25 13:42 UTC, meaboutsoftware commented on .github/workflows/ci.yml
> +    steps:
what about:

jobs:
build:
test:

? I mean to separate test from build, then you have first build, then test (you can use "needs: [build]")

2023-03-26 08:27 UTC, kamilbaczek commented on .github/workflows/ci.yml
> +    steps:
Yes I thought about this. I planned to do it in next MR. I can do it in first version. No problem :D

2023-03-26 08:39 UTC, kamilbaczek commented on .github/workflows/ci.yml
> +    steps:
Done. 

I love how it looks with GitHub client :D I have never seen this window before :D 
<img width="479" alt="image" src="https://user-images.githubusercontent.com/74410956/227764758-ce6cafcc-1d8a-4228-9d2a-d461d55f412b.png">

2023-03-26 15:25 UTC, meaboutsoftware approved these changes

2023-03-26 15:25 UTC, merged